repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    args: [ --max-line-length=120 ]
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    args: [ --max-line-length=120 ]
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    args: [ --max-line-length=120 ]
    args: [ --remove-all-unused-imports, --remove-unused-variables, --in-place ]
    hooks:
      - id: autoflake