# Generated by Django 5.0.1 on 2024-03-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("django_server", "0002_remove_post_tags"),
        ("django_server", "0003_post_tags"),
        ("django_server", "0004_tag2_remove_post_tags_delete_tag"),
        ("django_server", "0005_tag_post_tags"),
    ]

    dependencies = [
        ("django_server", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="django_server.tag"),
        ),
    ]
