# Generated by Django 5.0.1 on 2024-03-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_server", "0002_remove_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="django_server.tag"),
        ),
    ]
