# Generated by Django 4.2.3 on 2023-08-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0007_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_prompt',
            field=models.BooleanField(default=False),
        ),
    ]
