# Generated by Django 4.2.3 on 2023-08-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0009_postscore_commentscore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentscore',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postscore',
            unique_together={('user', 'post')},
        ),
    ]
