# Generated by Django 4.2.3 on 2023-08-16 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0011_alter_commentscore_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
