# Generated by Django 4.2.3 on 2023-08-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_server", "0013_alter_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                default="betrayedDoves6", max_length=255, unique=True
            ),
        ),
    ]
