# Generated by Django 4.2.4 on 2023-08-24 20:47

from django.db import migrations, models
import django_server.models


class Migration(migrations.Migration):
    dependencies = [
        ("django_server", "0014_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="chat_role",
            field=models.TextField(
                default="You are a helpful assistant.", max_length=65535
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                default=django_server.models.get_default_user_display_name,
                max_length=255,
                unique=True,
            ),
        ),
    ]
