# Generated by Django 4.2.4 on 2023-08-24 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_server", "0015_post_chat_role_alter_user_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post_id",
            new_name="post",
        ),
    ]
