# Generated by Django 4.2.4 on 2023-08-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_server", "0016_rename_post_id_comment_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="django_server.tag"),
        ),
    ]
