# Generated by Django 4.2.4 on 2023-08-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_server", "0001_squashed_0017_tag_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
