# Generated by Django 4.2.4 on 2023-09-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_server", "0020_remove_comment_parent_comment_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="prompt_mode",
            field=models.CharField(
                choices=[("author", "author"), ("score", "score")],
                default="author",
                max_length=255,
            ),
        ),
    ]
