# Generated by Django 4.2.4 on 2024-01-13 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_server", "0021_post_prompt_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="google_id",
        ),
    ]
