# Generated by Django 5.0.1 on 2024-02-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_server", "0022_remove_user_google_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="django_server.tag"),
        ),
    ]
