# Generated by Django 5.0.1 on 2024-02-17 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_server", "0023_alter_post_tags"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RenameField(
            model_name="user",
            old_name="email",
            new_name="username",
        ),
    ]
