# Generated by Django 5.0.1 on 2024-02-17 16:11

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_server",
            "0001_squashed_0017_tag_post_tags_squashed_0024_alter_user_managers_rename_email_user_username",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
