# Generated by Django 5.0.1 on 2024-02-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_server", "0025_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
