name: Docker Build and Push

on:
  push:
    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Restore cached virtual environment
        uses: actions/cache@v2
        id: restore-cache
        with:
          path: venv
          key: venv-${{ hashFiles('pyproject.toml') }}

      - name: Install Poetry and dependencies
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install poetry
          poetry install

      - name: Cache virtual environment
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: venv
          key: venv-${{ hashFiles('pyproject.toml') }}

      - run: ls

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: docker build .
