name: Docker Build and Push

on:
  push:
    branches:
      - main  # Adjust this branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Poetry and dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install poetry
          poetry install

      - name: Cache virtual environment
        uses: actions/cache@v2
        with:
          path: venv
          key: venv-${{ hashFiles('pyproject.toml') }}

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: docker build .
